import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Logo from "../../public/icons/logo.svg";

import IndeedLogo from "../../public/icons/indeed.webp";
import OshaLogo from "../../public/icons/osha.webp";
import RelativityLogo from "../../public/icons/relativity.svg";
import TRGLogo from "../../public/icons/trg.webp";

import ArrowIcon from "../../public/icons/arrowIcon.svg";
import Booklets from "../../public/icons/booklets.jpeg";
import BusinessCards from "../../public/icons/businessCards.jpeg";
import CaseStudy from "../../public/icons/caseStudyBG.jpeg";
import GreyCheck from "../../public/icons/checkGrey.svg";
import CommitIcon from "../../public/icons/commitIcon.svg";
import DisplaySignage from "../../public/icons/displaySignage.jpeg";
import DocIcon from "../../public/icons/docIcon.svg";
import EmployeeAparellIcon from "../../public/icons/employeeApparelIcon.svg";
import EmployeeIcon from "../../public/icons/employeeIcon.svg";
import Flyers from "../../public/icons/flyers.webp";
import Manuals from "../../public/icons/manuals.jpeg";
import OfficeIcon from "../../public/icons/officeIcon.svg";
import Postcards from "../../public/icons/postcards.jpeg";
import Presentations from "../../public/icons/presentations.jpeg";
import PrintIcon from "../../public/icons/printIcon.svg";
import PromotionalProducts from "../../public/icons/promotionalProducts.jpeg";
import RecruitmentIcon from "../../public/icons/recruitmentIcon.svg";
import ReduceIcon from "../../public/icons/reduceIcon.svg";
import SpeedyIcon from "../../public/icons/speedyIcon.svg";
import StarIcon from "../../public/icons/starIcon.svg";
import Step1 from "../../public/icons/step1.svg";
import Step2 from "../../public/icons/step2.svg";
import Step3 from "../../public/icons/step3.svg";
import Step4 from "../../public/icons/step4.svg";
import Step5 from "../../public/icons/step5.svg";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [clickedService, setClickedService] = useState(1)

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        ></link>
      </Head>
      <header className={styles.header}>
        <a href="#">
          <Image src={Logo} alt="Vseen for HR logo" height={42} width={104} />
        </a>
        <nav>
          <a href="#products">What we do</a>
          <a href="#process">Our process</a>
          <a href="#contact">Contact</a>
        </nav>
      </header>
      <main>
        <section className={styles.hero}>
          <div>
            <h1>Online Printing for HR Professionals</h1>
            <p>
              Managing a human relations department is complex. Printing doesn't
              have to be. With VSEEN FOR HR as your one-stop shop, you'll order
              company merchandise, recruitment supplies, and last-minute print
              from the same friendly team. Whether you need open enrollment
              paperwork, employee gifts, or job fair displays, we're here to
              help.
            </p>
            <a href="#">Get Started</a>
          </div>
        </section>
        <section className={styles.services}>
          <h2>One-Stop Shop for HR Needs</h2>
          <p>
            The average HR employee is pulled in way too many directions. Don't
            waste another second worrying about how to order custom print or
            branded materials. We're your one-stop shop for:
          </p>
          <div>
            <article>
              <Image src={EmployeeIcon}></Image>
              <h3>Employee Communications</h3>
              <p>
                New hire paperwork. Open enrollment reminders. Letters from the
                CEO. Whatever you need to print and mail to your employees, we
                make it as simple as upload and order. With delivery to up to
                500 residences per order, it's easy to keep tabs on each and
                every piece of mail.
              </p>
            </article>
            <article>
              <Image src={RecruitmentIcon}></Image>
              <h3>Recruitment Operations</h3>
              <p>
                Get in front of potential new hires without losing sleep over
                the logistics. Order custom banners and displays, branded table
                throws, unique SWAG, and last-minute brochures or flyers for job
                fairs.
              </p>
            </article>
            <article>
              <Image src={OfficeIcon}></Image>
              <h3>Office Stationery</h3>
              <p>
                Scale your business cards, notepaper, pens, and other
                company-branded office stationery. Order everything delivered to
                your department, or empower each office location to order their
                own (without giving up control of branding or budget).
              </p>
            </article>
            <article>
              <Image src={EmployeeAparellIcon}></Image>
              <h3>Employee Apparel and Gifts</h3>
              <p>
                Make sure your employees have the apparel they need to get the
                job done. Order branded hats, shirts, face masks, and other
                apparel. Plus, show some appreciation with employee gifts.
                Whatever you want to put your logo on, we'll procure, produce,
                and deliver.
              </p>
            </article>
          </div>
        </section>
        <section className={styles.socialProof}>
          <h2>Trusted by:</h2>
          <div>
            <Image src={IndeedLogo} width={186}></Image>
            <Image src={OshaLogo} width={186}></Image>
            <Image src={RelativityLogo} width={186}></Image>
            <Image src={TRGLogo} width={186}></Image>
          </div>
        </section>
        <section className={styles.products} id="products">
          <h2>What You Can Print With VSEEN FOR HR:</h2>
          <div>
            <article>
              <Image
                src={Booklets}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Booklets</p>
            </article>
            <article>
              <Image
                src={Manuals}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Manuals</p>
            </article>
            <article>
              <Image
                src={Flyers}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Flyers</p>
            </article>
            <article>
              <Image
                src={Presentations}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Presentations</p>
            </article>
            <article>
              <Image
                src={DisplaySignage}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Display Signage</p>
            </article>
            <article>
              <Image
                src={BusinessCards}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Business Cards</p>
            </article>
            <article>
              <Image
                src={PromotionalProducts}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Promotional Products</p>
            </article>
            <article>
              <Image
                src={Postcards}
                width={260}
                height={170}
                style={{ objectFit: "cover" }}
              ></Image>
              <p>Postcards</p>
            </article>
          </div>
          <a href="http://" target="_blank" rel="noopener noreferrer">
            Learn More
          </a>
        </section>
        <section className={styles.caseStudy}>
          <Image
            src={CaseStudy}
            fill={true}
            style={{ objectFit: "cover" }}
          ></Image>
          <div>
            <h2>
              How Spring Venture Group Saved 50% in New Hire Material Costs
            </h2>
            <p>
              When Spring Venture Group started hiring more remote employees
              than ever, Joe Sitler turned to VSEEN FOR HR for better print
              logistics. As a bonus, his print costs per project went down by
              50%.
            </p>
            <a href="">Read the Case Study</a>
          </div>
        </section>
        <section className={styles.serviceSelect}>
          <h2>Complex Services to Make Your HR Operations Simple</h2>
          <p>
            We plug into your team with an array of solutions to make your life
            easier.
          </p>
          <div className={styles.serviceSelectListContainer}>
            <div className={styles.serviceSelectList}>
              <div onClick={() => setClickedService(1)}>
                <p>VSEEN FOR HR Print</p>
                <svg
                  version="1.1"
                  id="Layer_1"
                  viewBox="0 0 512 512"
                  width={20}
                >
                  <path
                    className={ clickedService == 1 ? styles.active : ''}
                    d="M335,408.1c-4.7-3.8-7-9.9-7-16.1s2.3-12.3,7-17l95.1-95H24c-13.2,0-24-10.8-24-24.9C0,242.7,10.8,232,24,232
	h406.1l-95-95c-9.4-9.4-9.4-24.6,0-33.9s24.6-9.4,33.9,0l136,136c9.4,9.4,9.4,24.6,0,33.9L369,409
	C359.6,418.3,344.4,418.3,335,408.1z"
                  />
                </svg>
              </div>
              <div onClick={() => setClickedService(2)}>
                <p>Custom SWAG</p>
                <svg
                  version="1.1"
                  id="Layer_1"
                  viewBox="0 0 512 512"
                  width={20}
                >
                  <path
                    className={ clickedService == 2 ? styles.active : ''}
                    d="M335,408.1c-4.7-3.8-7-9.9-7-16.1s2.3-12.3,7-17l95.1-95H24c-13.2,0-24-10.8-24-24.9C0,242.7,10.8,232,24,232
	h406.1l-95-95c-9.4-9.4-9.4-24.6,0-33.9s24.6-9.4,33.9,0l136,136c9.4,9.4,9.4,24.6,0,33.9L369,409
	C359.6,418.3,344.4,418.3,335,408.1z"
                  />
                </svg>              </div>
              <div onClick={() => setClickedService(3)}>
                <p>Branded Displays</p>
                <svg
                  version="1.1"
                  id="Layer_1"
                  viewBox="0 0 512 512"
                  width={20}
                >
                  <path
                    className={ clickedService == 3 ? styles.active : ''}
                    d="M335,408.1c-4.7-3.8-7-9.9-7-16.1s2.3-12.3,7-17l95.1-95H24c-13.2,0-24-10.8-24-24.9C0,242.7,10.8,232,24,232
	h406.1l-95-95c-9.4-9.4-9.4-24.6,0-33.9s24.6-9.4,33.9,0l136,136c9.4,9.4,9.4,24.6,0,33.9L369,409
	C359.6,418.3,344.4,418.3,335,408.1z"
                  />
                </svg>              </div>
              <div onClick={() => setClickedService(4)}>
                <p>Direct Mail Services</p>
                <svg
                  version="1.1"
                  id="Layer_1"
                  viewBox="0 0 512 512"
                  width={20}
                >
                  <path
                    className={ clickedService == 4 ? styles.active : ''}
                    d="M335,408.1c-4.7-3.8-7-9.9-7-16.1s2.3-12.3,7-17l95.1-95H24c-13.2,0-24-10.8-24-24.9C0,242.7,10.8,232,24,232
	h406.1l-95-95c-9.4-9.4-9.4-24.6,0-33.9s24.6-9.4,33.9,0l136,136c9.4,9.4,9.4,24.6,0,33.9L369,409
	C359.6,418.3,344.4,418.3,335,408.1z"
                  />
                </svg>              </div>
            </div>
            <div className={styles.serviceSelectContent}>
              <h3>title</h3>
              <p>text</p>
              <a>button</a>
            </div>
          </div>
        </section>
        <section className={styles.process} id="process">
          <h2>Getting Started</h2>
          <ul>
            <div className={styles.line}></div>
            <li className={styles.step1}>
              <Image src={Step1} width={110} height={110}></Image>
              <p>Tell Us Your Goals</p>
              <div className={styles.circle}></div>
            </li>
            <li className={styles.step2}>
              <Image src={Step2} width={110} height={110}></Image>
              <p>Get a Demo + Samples</p>
              <div className={styles.circle}></div>
            </li>
            <li className={styles.step3}>
              <Image src={Step3} width={110} height={110}></Image>
              <p>Plug In Your Documents</p>
              <div className={styles.circle}></div>
            </li>
            <li className={styles.step4}>
              <Image src={Step4} width={110} height={110}></Image>
              <p>Place Your First Order</p>
              <div className={styles.circle}></div>
            </li>
            <li className={styles.step5}>
              <Image src={Step5} width={110} height={110}></Image>
              <p>Rejoice, Repeat, and Grow</p>
              <div className={styles.circle}></div>
            </li>
          </ul>
        </section>
        <section className={styles.benefits}>
          <h2>Partners Beyond One Project</h2>
          <p>
            Set your team up for success with a print partner who is here for
            the long term.
          </p>
          <div>
            <article>
              <Image src={DocIcon} ></Image>
              <h3>5,561,495 Documents Delivered and Counting</h3>
              <p>
                We've been printing and delivering business documents for 20+
                years, so we know a thing or two about long-term relationships
              </p>
            </article>
            <article>
              <Image src={SpeedyIcon} ></Image>
              <h3>Speedy Global Delivery</h3>
              <p>
                Whether your documents are going to Tennessee or Timbuktu, we
                guarantee the same quality of print at budget-friendly prices
              </p>
            </article>
            <article>
              <Image src={ReduceIcon} ></Image>
              <h3>Reduce Costs and Uncertainty</h3>
              <p>
                No order minimums means you can order the exact number of
                documents you need today, rather than guessing at how many
                you'll use over the year
              </p>
            </article>
            <article>
              <Image src={CommitIcon} ></Image>
              <h3>Committed to Protecting Your Privacy</h3>
              <p>
                Your security is our top priority, which is why Fortune 1000
                companies trust us with their data and documents
              </p>
            </article>
            <article>
              <Image src={PrintIcon} ></Image>
              <h3>Print with Sustainability in Mind</h3>
              <p>
                We're committed to sustainable printing and shipping so that you
                don't have to worry about it
              </p>
            </article>
            <article>
              <Image src={StarIcon} ></Image>
              <h3>5-Star Customer Support Team</h3>
              <p>
                No matter how small your questions, our award-winning, US-based
                24/7/365 customer support is here to help
              </p>
            </article>
          </div>
        </section>
        <section>
          <h2></h2>
          <p></p>
        </section>
        <section className={styles.contact} id="contact">
          <div>
            <h2>Get Started</h2>
            <p>Schedule a call to take our system for a test drive.</p>
            <p>
              It's easy to print your business documents online with VSEEN FOR
              HR
            </p>
            <ul>
              <li>
                <Image src={GreyCheck}></Image> <span>No Order Minimums</span>
              </li>
              <li>
                <Image src={GreyCheck}></Image> <span>Print from Wherever You Are</span>
              </li>
              <li>
                <Image src={GreyCheck}></Image> <span>Budget-Friendly Prices</span>
              </li>
              <li>
                <Image src={GreyCheck}></Image> <span>Overnight Delivery</span>
              </li>
              <li>
                <Image src={GreyCheck}></Image> <span>API Integration</span>
              </li>
              <li>
                <Image src={GreyCheck}></Image> <span>Warehousing</span>
              </li>
            </ul>
            <p>
              <strong> Questions? call us at</strong> <a href="" style={{textDecoration: 'underline'}}>1.800.000.000</a>
            </p>
          </div>
          <form>
            <div>
              <label>
                <span>First Name</span>
                <input type="text" />
              </label>
              <label>
                <span>Last Name</span>
                <input type="text" />
              </label>
            </div>
            <div>
              <label>
                <span>Company Email</span>
                <input type="text" />
              </label>
              <label>
                <span>Company</span>
                <input type="text" />
              </label>
            </div>
            <div>
              <label>
                <span>Job Title</span>
                <input type="text" />
              </label>
              <label>
                <span># Of Employees</span>
                <input type="text" />
              </label>
            </div>
            <div>
              <label>
                <span>Phone</span>
                <input type="text" />
              </label>
              <label>
                <span>How did you hear about us?</span>
                <input type="text" />
              </label>
            </div>
            <p>I'm not a robot</p>
            <button type="submit">Submit</button>
            <span className={styles.small}>
              By submitting this form, you hereby accept that your personal data
              will be collected and processed for contact purposes. For example,
              by sharing your name and contact information, we may contact you
              about upcoming events, educational resources, or product updates.
              We respect your privacy and do not tolerate spam; please consult
              our Data Privacy Policy for additional information
            </span>
          </form>
        </section>
      </main>
    </>
  );
}
